

services:
  documentation:
    image: squidfunk/mkdocs-material:latest
    container_name: mkdocs_junior
    command: serve --dev-addr=0.0.0.0:8010 --watch-theme
    restart: unless-stopped
    ports:
      - "8100:8010"
    volumes:
      - ./documentation:/docs:ro

  database:
    image: postgres:16-alpine
    container_name: database
    hostname: local_database
    restart: always
    env_file:
      - .env
    ports:
      - "6655:5432"
    volumes:
      - postgres_datastorage:/var/lib/postgresql/data
    networks:
      - main_network

networks:
  main_network:
    driver: bridge

volumes:
  postgres_datastorage:
    external: false
